export const ROLES = {
  STUDENT: 'STUDENT',
  TEACHER: 'TEACHER',
  COUNSELOR: 'COUNSELOR',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
} as const;

export const ATTENDANCE_STATUS = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  PARTIAL: 'PARTIAL',
  EXCUSED: 'EXCUSED',
  OVERRIDE: 'OVERRIDE',
} as const;
